[package]
name = "raptor"
description = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[[bin]]
bench = false
path = "src/main.rs"
name = "raptor"

[dependencies]
anyhow = { workspace = true }
# ptree = { workspace = true }
inquire = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { version = "4.4", features = ["derive"] }
